### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by TheCrazyT** [TheCrazyT/x64dbg-plugin-quickaccess#11]
According to https://github.com/TheCrazyT/x64dbg-plugin-quickaccess/issues/9#issuecomment-1381386209 window size of dropdown is not optimal.
Changing the code seem to produce problems.

**Comment by TheCrazyT** [comment]
@jindili
see https://github.com/TheCrazyT/x64dbg-plugin-quickaccess/blob/window-size/quickaccess.cpp#L79
The Trick is to cast popup to QListView.

(binaries are here: https://ci.appveyor.com/project/TheCrazyT/x64dbg-plugin-quickaccess/builds/45937249/job/otvyen3nq26bus8r/artifacts)

**Comment by jindili** [comment]
cool, now there is more space to show infomation:
![image](https://user-images.githubusercontent.com/73845/212463540-13ac9a27-6204-416a-b4bb-52210e484fca.png)

**Comment by jindili** [comment]
@TheCrazyT 
This issue can be closed now since it's working as expected.

**Comment by TheCrazyT** [comment]
@jindili I'm actually thinking about adding some menu entries to set the window size.
But at the moment I can't decide where I should store the settings.
(ini-file in application directory or user directory? Or just in the windows registry?)

**Comment by jindili** [comment]
I prefer user directory or just in the Windows registry
As x64dbg updates frequently, it would be better to keep the user settings.
