### ISSUE TITLE
Version 1.4.87 cause x64dbg crash on start

### ISSUE THREAD

**Issue by jindili** [TheCrazyT/x64dbg-plugin-quickaccess#8]
x64dbg version:
snapshot_2022-12-12_15-45.zip (latest version from github release)

I try quickaccess.dp64 with all other plugins removed.

version 1.4.82 work fine.

**Comment by TheCrazyT** [comment]
you are right, it seems to crash at:
https://github.com/TheCrazyT/x64dbg-plugin-quickaccess/blob/3d0c3e1f7482be96976f16829feef2e21a844efa/pluginmain.cpp#L98
Maybe some libs inside `pluginsdk `are outdated.
I will try to figure it out ...

**Comment by TheCrazyT** [comment]
hm, a reason for this is a returned null-pointer at:
https://github.com/TheCrazyT/x64dbg-plugin-quickaccess/blob/3d0c3e1f7482be96976f16829feef2e21a844efa/pluginmain.cpp#L97

Wonder why it suddenly can't get an active window.

**Comment by jindili** [comment]
Just build with appveyor and successfully get a new release of quickaccess.dp64
but still it cause x64dbg to crash on start.

**Comment by TheCrazyT** [comment]
yes, I already noticed that the libs aren't the problem.
Sadly I do not know yet, what else could cause that behaviour.

**Comment by TheCrazyT** [comment]
@mrexodia do you have any idea?

**Comment by jindili** [comment]
Here is the screenshot of minidump file of the crash open in windbg preview
![image](https://user-images.githubusercontent.com/73845/211133852-0e539b4f-e168-4cad-ba3e-e5d79b9e38e2.png)

**Comment by TheCrazyT** [comment]
@jindili try with newest release of the plugin, it should work now.

**Comment by mrexodia** [comment]
Glad it was fixed. Not sure if I introduced this issue, but maybe the order of operations at load time was changed?

**Comment by jindili** [comment]
It works!
Like the new fuzzy search.
