### ISSUE TITLE
[Feature Request] Is that possible to add search for Actions

### ISSUE THREAD

**Issue by jindili** [TheCrazyT/x64dbg-plugin-quickaccess#9]
Like those actions in Hotkeys editor:
![image](https://user-images.githubusercontent.com/73845/211230856-0cdfc79d-87b1-4022-acf6-1b40a5a543d7.png)

**Comment by TheCrazyT** [comment]
I'm not shure if thats useful, but you can download a test-version here (quickaccess.dp64): 
https://ci.appveyor.com/project/TheCrazyT/x64dbg-plugin-quickaccess/builds/45895263/job/e8w4qx7fpa7uxwou/artifacts

But it currently has a bug with some duplicates.
Not shure why they appear, guess I will figure it out later ...

**Comment by jindili** [comment]
Just tried, It works great and helpful for me.

though some duplicate:
![image](https://user-images.githubusercontent.com/73845/211684689-ac066925-6765-4a82-8ff6-96b3c03bab4d.png)

I think it might be because the search result is combined of search result from Menus, Actions or even content menus.
in Hotkeys editor there is a command path indicated with "->":
![image](https://user-images.githubusercontent.com/73845/211685110-9956bd89-060c-4060-80c4-2c14a86401b0.png)

**Comment by TheCrazyT** [comment]
@jindili 
should looke like that now:

![references](https://user-images.githubusercontent.com/498863/211871153-5a6a410e-0013-4091-83a2-f5905a3b06b8.png)

newest build:
https://ci.appveyor.com/project/TheCrazyT/x64dbg-plugin-quickaccess/builds/45907396/job/aaenfrnfprj7npq8/artifacts

**Comment by jindili** [comment]
Much better now:
![image](https://user-images.githubusercontent.com/73845/211942456-1b81ea1e-d933-4fb9-a317-76e107a00aec.png)

could I configure the size of result window to make it bigger, to about size like this:
![image](https://user-images.githubusercontent.com/73845/211942726-ccc32363-27ea-48ec-a894-5acf84b645e5.png)

**Comment by TheCrazyT** [comment]
@jindili 
nope.
I'm afraid, there is no config-menu at all for this plugin.

**Comment by jindili** [comment]
I can't find places in the code to change parameter value like width or height and rebuild.
Can you tell me where to set width and height in the source ?

**Comment by TheCrazyT** [comment]
that is probably possible by changing `QCompleter`
https://stackoverflow.com/questions/31585184/qt-qcompleter-cant-have-its-size-set might help

**Comment by jindili** [comment]
I add these two line to set popup width and height:
![image](https://user-images.githubusercontent.com/73845/212254882-2fcd8fa9-b442-4070-8398-07056f0d355e.png)

build error in appveyor:
```
.\quickaccess.cpp(77) : error C2027: use of undefined type 'QAbstractItemView'
        c:\qt\5.6\msvc2013_64\include\qtwidgets\qcompleter.h(49) : see declaration of 'QAbstractItemView'
.\quickaccess.cpp(77) : error C2227: left of '->setMinimumWidth' must point to class/struct/union/generic type
Generating Code...
```
